### ISSUE TITLE
As a new user, I would like to be able to register for a new acount

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/task-productivity#10]
# User Scenario
A user wants to signup for the service. 

# Expected Behavior of the Program
- [x] The system will sign the user up if my username and email are both unique. 
- [x] The system will only sign the user up when post entered passwords are correct along with the previous condition.
- [x] If the username or email exists then it will let the user know. 
- [x] If the passwords don't match, it will let the user know. 
- [x] If the password is not secure enough, it will let the user know. 
- [ ] It will send an email to the user to confirm his / her email. 
- [ ] The verification email will only be valid for 1 hour.

# Todo
- [x] Update the database design diagram to include a verified column. 
- [x] Design the signup UI. 
- [x] Write the route to verify that the username and email don't exist. 
- [x] Find out how to send an email through an email service. 
- [ ] Write the route for email verification. 
- [x] Write user creation route. It should still verify if the email and username exist or not. 
- [x] Find out the best practice of writing tests for external APIs. 

### Route Testing
- [x] Username doesn't exist verification. (Scenario where the username exists and doesn't exist)
- [x] Email doesn't exist verification. (Scenario where the email exists and doesn't exist)
- [x] The user creation route. It will test the scenario when a username exists, an email exists and the case when both doesn't exist. 
- [ ] It will test if the email is being sent out or not. (Find out how to test external APIs). 
- [ ] User email verification route test. 
### Selenium
- [x] Check the signup page
- [ ] Check the verification page

**Comment by chuaweijie** [comment]
Possible references for API tests. 

https://stackoverflow.com/questions/50157543/unittest-django-mock-external-api-what-is-proper-way
https://docs.djangoproject.com/en/3.2/topics/testing/tools/

**Comment by chuaweijie** [comment]
For speed purposes, no tests are written and this requirement is closed by b64d58138796452cbd326dc5f2bbcbddc457054e

**Comment by chuaweijie** [comment]
The project will be archived hence no new development will be done.
