### ISSUE TITLE
As a user, I would like to be able to track my current 90 days reporting and my past reportings.

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/task-productivity#13]
# User Scenario
I've successfully logged in into the system. I want to start tracking my 90 days reporting. Things that I might want to do. 
1. Add a new 90 days reporting tracking. 
2. They want to update the fact that they've successfully finished the 90 days reporting and they would like to add a new date. 
3. They might want to review their current 90 days reporting date. 
4. They might want to check their historical reporting date. 

# Expected Behavior of the Program
- [x] The system will load the current active tracking by default. If there is no active tracking, the add button will be showing. 
- [x] If there is an active tracking, the user could choose to either delete it, edit it or mark as done.
- [x] Once the tracking is mark done, it will be transferred to the history page. Deleted tracking will not be transferred to historical page. 
- [x] There will be a button where the system will load the historical tracking. The user can only undo the record that is marked as done today. 

# Todo
- [x] Design the UI. 
- [x] Write a route to list the active tracking. 
- [x] Write a route to list the historical tracking.
- [x] Write a route to accept JSON posting of a new tracking.
- [x] Write a route to accept the deletion of a current tracking.
- [x] Write a route to mark tracking as done. 
- [x] Write a route to undo mark tracking as done. 
- [x] Write the React one page app. 

### Route Testing
- [x] A test to check if the route returns the list of active tracking correctly. 
- [x] A test to check if the route returns the list of historical tracking correctly. 
- [x] A test to check if the JSON posting of worked correctly
- [x] A test to check if the deletion of the current tracking worked correctly.
- [x] A test to check if the mark as done of the current tracking worked correctly.
- [x] A test to check if the undo mark as done of the current tracking worked correctly.
