### ISSUE TITLE
As an unregistered user, I would like to see a website that illustrates the features of this website with sign up and login buttons.

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/task-productivity#6]
# User Scenario
The user might've reached your site through a result from a search listing or a recommendation from a friend. They might also be a returning user. They might want to achieve one of the following objectives. 
1. To find out what this website is about. 
2. They would like to sign up for the service. 
3. They might be a returning user who wants to log in to the service. 

# Expected Behavior of the Program
- [x] There will be a sign-up button. Clicking upon this button will bring the user to the signup page.
- [x] There will be a login button. Clicking upon this button will bring the user to the login page.
- [x] This page will illustrate the features of this website. 

# Todo
- [x] Design the homepage.
- [x] Write the copy of the hompeage.
- [x] Code the homepage.

### Route Testing
- [x] Test index route. 
### Selenium
- [x] Test the existence of the login and sign-up button.

**Comment by chuaweijie** [comment]
Requirement should be closed by 399f67aadf5b7755c6b209396b570ba67d3836fe
