### ISSUE TITLE
As a registered user, I would like to login into the website

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/task-productivity#8]
# User Scenario
The user is a registered user who wants to log in to use the service. 

# Expected Behavior of the Program
- [ ] If the username or the password is incorrect, it will show the error message without letting the user know if the user exists or not. 
- [ ] The user can use the username or registered email to log in. 
- [ ] Once the user entered the correct username and email, he/she will be logged in to the system. 
If the user doesn't remember his/her username or password, he/she will be able to use the forget password function to recover his/her account. (This will be handled by #9)

# Todo
- [ ] Design the login page.
- [ ] Write the login page.
- [ ] Code the HTML, CSS and views of login page.

### Route Testing
- [ ] Test getting login page
- [ ] Test login POST route with incorrect username. 
- [ ] Test login POST route with incorrect password. 
- [ ] Test login POST route with correct username and password. 
### Selenium
- [ ] Test login with incorrect username. 
- [ ] Test login with incorrect password. 
- [ ] Test login with correct username and password.

**Comment by chuaweijie** [comment]
For speed purposes, no tests are written and this requirement is closed by b64d58138796452cbd326dc5f2bbcbddc457054e
