### ISSUE TITLE
As a user, I would like to be able to reset my password if I forgot my password

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/task-productivity#9]
# User Scenario
The user forgot about his/her password. 

# Expected Behavior of the Program
- [ ] The system will verify if the user exists or not by sending an email to the user if his or her account exists. If it doesn't exist, it will an email inviting them to join our service. Both scenarios will show the user that a recovery email has been sent to the email that he or she registered with us. 
- [ ] The email link will be valid for 1 hour. 
- [ ] If the email link is clicked after 1 hour then it will show that the link is invalid. It will also show a link that leads to the forgotten password page. 
- [ ] If the email link is clicked before the 1-hour limit then the browser will show them the reset password page. 
- [ ] If both passwords are the same then the user's password will be updated. 

# Todo
- [ ] Update the database design diagram to include an expiry column and recovery key. 
- [ ] Write the password recovery request page. 
- [ ] Write the change password page.
- [ ] Write the recovery logic. If the link is generated within 1 hour then return the change password page. If not return an error message.

### Route Testing
- [ ] Test getting the recovery request page. 
- [ ] Test getting the change password page without any recovery key.
- [ ] Test getting the change password page with a fake key.
- [ ] Test posting the recovery request with an existing username.
- [ ] Test posting the recovery request with an existing email.
- [ ] Test posting the recovery request with a non-existing username.
- [ ] Test posting the recovery request with a non-existing email. 
- [ ] Test changing password with a valid link to the change password page. 
- [ ] Test loading the change password with an invalid change password page link. 
### Selenium
- [ ] Test the elements in the recovery request page. 
- [ ] Test getting the change password page without any recovery key.
- [ ] Test getting the change password page with a fake key.
- [ ] Test posting the recovery request with an existing username.
- [ ] Test posting the recovery request with an existing email.
- [ ] Test posting the recovery request with a non-existing username.
- [ ] Test posting the recovery request with a non-existing email. 
- [ ] Test changing password with a valid link to the change password page. Check elements and the page logic.
- [ ] Test loading the change password with an invalid change password page link.

**Comment by chuaweijie** [comment]
Not going to implement until further notice.
